#!/bin/sh
preselection='pt_1>25&&pt_2>20&&npv>0&&diLeptons==0&&iso04_1<0.15&&byTightIsolationMVArun2v1DBoldDMwLT_2>0.5&&tightMuons<=1&&tightElectrons==0&&againstMuonTight3_2>0&&againstElectronVLooseMVA6_2>0&&diLeptons==0&&(HLT_IsoMu24_v_fired>0||HLT_IsoTkMu24_v_fired>0)'
preselection0='pt_1>25&&pt_2>20&&npv>0&&diLeptons==0&&iso04_1<0.15&&byTightIsolationMVArun2v1DBoldDMwLT_2>0.5&&tightMuons<=1&&tightElectrons==0&&againstMuonTight3_2>0&&againstElectronVLooseMVA6_2>0&&diLeptons==0&&(HLT_IsoMu24_v_fired>0||HLT_IsoTkMu24_v_fired>0)&&tauDecayMode==0'
preselection1='pt_1>25&&pt_2>20&&npv>0&&diLeptons==0&&iso04_1<0.15&&byTightIsolationMVArun2v1DBoldDMwLT_2>0.5&&tightMuons<=1&&tightElectrons==0&&againstMuonTight3_2>0&&againstElectronVLooseMVA6_2>0&&diLeptons==0&&(HLT_IsoMu24_v_fired>0||HLT_IsoTkMu24_v_fired>0)&&tauDecayMode==1'
preselection10='pt_1>25&&pt_2>20&&npv>0&&diLeptons==0&&iso04_1<0.15&&byTightIsolationMVArun2v1DBoldDMwLT_2>0.5&&tightMuons<=1&&tightElectrons==0&&againstMuonTight3_2>0&&againstElectronVLooseMVA6_2>0&&diLeptons==0&&(HLT_IsoMu24_v_fired>0||HLT_IsoTkMu24_v_fired>0)&&tauDecayMode==10'
wselection='pfmt_1>80'
signalselection='pfmt_1<50'
zerojselection='njets==0&&pt_2>20&&pt_2<50'
zerojhighselection='njets==0&&pt_2>50'
onejselection='(njets==1||(njets==2&&vbfMass<500))&&(pt_2<40||pt_sv<140)&&pt_2>30'
#onejselection='njets==1&&((pt_2>30&&pt_2<40)||(pt_2>40&&pt_sv<140))'
onejboostselection='(njets==1||(njets==2&&vbfMass<500))&&(pt_2>40&&pt_sv>140)&&pt_2>30'
#onejboostselection='((njets==1&&pt_2>40&&pt_sv>140)||(njets==2&&pt_sv>100&&vbfMass<500))'
vbfselection='njets==2&&((vbfMass>500&&vbfMass<800)||(vbfMass>500&&pt_sv<100))'
vbfselectionHiggs=$vbfselection
vbfhighselection='njets==2&&vbfMass>800&&pt_sv>100'
vbfhighselectionHiggs=$vbfhighselection
qcdselection=$preselection
trigselection='(HLT_IsoMu24_v_fired>0||HLT_IsoTkMu24_v_fired>0)' #only for MC
trigselectiondata='(HLT_IsoMu24_v_fired>0||HLT_IsoTkMu24_v_fired>0)' #only for Data
relaxedSelection='pt_1>25&&pt_2>20&&npv>0&&diLeptons==0&&iso04_1<0.3&&byMediumIsolationMVArun2v1DBoldDMwLT_2>0.5&&tightMuons<=1&&tightElectrons==0&&againstMuonTight3_2>0&&againstElectronVLooseMVA6_2>0'
luminosity=36812. #pb
direc='/nfs_scratch/laura/monohiggs_2/'
#direc='/nfs_scratch/laura/SMHiggs_mvis_unweighted1/'
datadirec=$direc
zttScale=1.
topWeight=1.0
#topWeight='topWeight'
#zlftFactor=1.0
zlftFactor='MuTauFake'
zWeight=1.0
#zWeight='__ZWEIGHT__'
tauID=0.95
qcdfactor=1.00
bTagSF=1.0

bins=30

binning='binningHighStat=0.,10.,20.,30.,40.,50.,60.,70.,80.,90.,100.,110.,120.,130.,140.,150.,160.,170.,180.,190.,200.,225.,250.,275.,300.,325.,350. binningLowStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,180.,200.,250.,300.,350.' 

mkdir tauES

MakeDataCardHTT channel='muTau' shifts='Tau' dataFile=$datadirec'muDATA.root' qcdFile=$direc'muDATA.root' zttFile=$direc'ZJETS.root' zllFile=$direc'ZJETS.root'  wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'TT.root' preselection=$preselection  wselection=$wselection  relaxedSelection=$relaxedSelection trigselection=$trigselection trigselectiondata=$trigselectiondata  signalselection='pfmt_1<50'   luminosityErr=0.045 qcdfactor=$qcdfactor qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  bTagSF=$bTagSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=$tauID tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17 bitmask=1,0,0,0 TTweight=$topWeight Zweight=$zWeight weight='__WEIGHT__*GENWEIGHT*puweight*idisoweight_1*trigweight_1'  luminosity=$luminosity  variable='m_vis' bins=30 min=0 max=150 outputFile='tauES/muTau_m_vis.root'  
exit;
nohup MakeDataCardHTT channel='muTau'  shifts='Tau' dataFile=$datadirec'muDATA.root' qcdFile=$direc'muDATA.root' zttFile=$direc'ZJETS.root' zllFile=$direc'ZJETS.root'  wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'TT.root' preselection=$preselection0  wselection=$wselection  relaxedSelection=$relaxedSelection trigselection=$trigselection trigselectiondata=$trigselectiondata  signalselection='pfmt_1<50'   luminosityErr=0.045 qcdfactor=$qcdfactor qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  bTagSF=$bTagSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=$tauID tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17 bitmask=1,0,0,0 TTweight=$topWeight Zweight=$zWeight weight='__WEIGHT__*GENWEIGHT*puweight*idisoweight_1*trigweight_1'  luminosity=$luminosity  variable='m_vis' bins=30 min=0 max=150 outputFile='tauES/muTau_m_vis_0.root' & 
nohup MakeDataCardHTT channel='muTau' shifts='Tau' dataFile=$datadirec'muDATA.root' qcdFile=$direc'muDATA.root' zttFile=$direc'ZJETS.root' zllFile=$direc'ZJETS.root'  wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'TT.root' preselection=$preselection1  wselection=$wselection  relaxedSelection=$relaxedSelection trigselection=$trigselection trigselectiondata=$trigselectiondata  signalselection='pfmt_1<50'   luminosityErr=0.045 qcdfactor=$qcdfactor qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  bTagSF=$bTagSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=$tauID tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17 bitmask=1,0,0,0 TTweight=$topWeight Zweight=$zWeight weight='__WEIGHT__*GENWEIGHT*puweight*idisoweight_1*trigweight_1'  luminosity=$luminosity  variable='m_vis' bins=30 min=0 max=150 outputFile='tauES/muTau_m_vis_1.root' & 
nohup MakeDataCardHTT channel='muTau' shifts='Tau'  dataFile=$datadirec'muDATA.root' qcdFile=$direc'muDATA.root' zttFile=$direc'ZJETS.root' zllFile=$direc'ZJETS.root'  wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'TT.root' preselection=$preselection10  wselection=$wselection  relaxedSelection=$relaxedSelection trigselection=$trigselection trigselectiondata=$trigselectiondata  signalselection='pfmt_1<50'   luminosityErr=0.045 qcdfactor=$qcdfactor qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  bTagSF=$bTagSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=$tauID tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17 bitmask=1,0,0,0 TTweight=$topWeight Zweight=$zWeight weight='__WEIGHT__*GENWEIGHT*puweight*idisoweight_1*trigweight_1'  luminosity=$luminosity  variable='m_vis' bins=30 min=0 max=150 outputFile='tauES/muTau_m_vis_10.root' & 

exit;
